import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/footer/Footer';
import SideBar from '@/components/navigation/sideBar/SideBar';
import NavBar from '@/components/navigation/navBar/NavBar';
import Logo from '@/components/logo/Logo';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="mx-auto px-4 max-w-3xl sm:px-6 xl:max-w-5xl xl:px-16">
          <div className="page-container flex flex-col  max-w-3xl">
            <header className=" flex flex-row justify-between items-center py-10">
              <Logo />
              <NavBar />
            </header>
            <div className="content-container flex flex-row">
              <div className="menu  basis-1/5 bg-[var(--bgSoft)] p-5 min-h-screen">
                <SideBar />
              </div>
              <div className="content basis-4/5 p-5">
                {children}
                <Footer></Footer>
              </div>
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
