import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import SideBar from "@/components/navigation/sideBar/SideBar";
import NavBar from "@/components/navigation/navBar/NavBar";
import Logo from "@/components/logo/Logo";
import Hamburger from "@/components/hamburger/Hamburger";

import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="mx-auto w-fit px-4 max-w-6xl sm:px-6 xl:max-w-4xl xl:px-16">
          <div className="page-container flex flex-col  w-full">
            <header className=" flex flex-row justify-between items-center py-10 max-[425px]:py-3">
              <Logo />
              <NavBar />
              <Hamburger />
            </header>
            <div className="content-container flex flex-row w-full">
              <div className=" menu min-w-[25%]  bg-[var(--bgSoft)] p-2 min-h-screen max-[900px]:hidden">
                <SideBar />
              </div>
              <div className="content flex flex-col w-full  p-1">
                {children}
                <Footer></Footer>
              </div>
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
